=== xi-yang/StackV.community/StackV-web/src/main/webapp/data/xml/intent.xsd
<?xml version="1.0"?>
<!--
Copyright (c) 2013-2017 University of Maryland
Created by: Alberto Jimenez

Permission is hereby granted, free of charge, to any person obtaining a copy 
of this software and/or hardware specification (the “Work”) to deal in the 
Work without restriction, including without limitation the rights to use, 
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
the Work, and to permit persons to whom the Work is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in 
all copies or substantial portions of the Work.

THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS  
IN THE WORK.
-->

<!--

* Requirements for intents:
    - Staging/pagination for inputs
    - Support for multiple instances of inputs
    - Support for accessing API for sourcing input values
    - Support for input defaults
    - Support for conditional stages/inputs

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">          
    
    <!--Simple-->
    <xs:attribute name="factory" type="xs:boolean"/>
    <xs:attribute name="collapsible" type="xs:boolean"/>
    <xs:attribute name="proceeding" type="xs:boolean"/>
    <xs:attribute name="passthrough" type="xs:boolean"/>
    <xs:attribute name="required" type="xs:boolean"/>
    <xs:attribute name="return" type="xs:boolean"/>
    
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="trigger" type="xs:string"/>
    <xs:attribute name="hidden" type="xs:string"/>
    <xs:attribute name="condition" type="xs:string"/>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="opened" type="xs:string"/>
    <xs:attribute name="block" type="xs:string"/>
    <xs:attribute name="start" type="xs:string"/>
    <xs:attribute name="default" type="xs:string"/>
    <xs:attribute name="label" type="xs:string"/>
    
    <xs:element name="name" type="xs:string"/>
    <xs:element name="type" type="xs:string"/>
    <xs:element name="location" type="xs:string"/>
    <xs:element name="tag" type="xs:string"/>
    <xs:element name="has" type="xs:string"/>
    <xs:element name="size" type="xs:string"/>    
    <xs:element name="initial" type="xs:string"/>    
    <xs:element name="interval" type="xs:string"/>
    <xs:element name="url" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="hint" type="xs:string"/>
    <xs:element name="text" type="xs:string"/>
    <xs:element name="parent" type="xs:string"/>
    <xs:element name="valid" type="xs:string"/>
    <xs:element name="regex" type="xs:string"/>
    <xs:element name="message" type="xs:string"/>
    <xs:element name="max" type="xs:string"/>
    <xs:element name="min" type="xs:string"/>
    
    <!--Complex-->
    <xs:element name="intent">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="meta"/>
                <xs:element ref="stage" maxOccurs="10"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="meta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="block" minOccurs="0" maxOccurs="10"/>
                <xs:element ref="validation" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="validation">
        <xs:complexType>
            <xs:sequence>                
                <xs:element ref="constraint" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="stage">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="group" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="condition"/>
            <xs:attribute ref="proceeding"/>
            <xs:attribute ref="return"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="group">
        <xs:complexType>
            <xs:sequence>                
                <xs:element ref="bound" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="fulfilled" minOccurs="0"/>      
                <xs:element ref="path" minOccurs="0"/>              
                <xs:element ref="group" minOccurs="0" maxOccurs="unbounded"/>                
                <xs:element ref="input" minOccurs="0" maxOccurs="unbounded"/>                
                <xs:element ref="group" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="factory" default="false"/>
            <xs:attribute ref="block"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="condition"/>
            <xs:attribute ref="passthrough"/>
            <xs:attribute ref="collapsible" default="false"/>
            <xs:attribute ref="opened"/>
            <xs:attribute ref="label" default="true"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="input">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="type"/>                
                <xs:element ref="default" minOccurs="0"/>
                <xs:element ref="hint" minOccurs="0"/>                                                
                <xs:element ref="link" minOccurs="0"/>
                <xs:element ref="options" minOccurs="0"/>
                <xs:element ref="size" minOccurs="0"/>
                <xs:element ref="source" minOccurs="0"/>                                
                <xs:element ref="valid" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute ref="required"/>
            <xs:attribute ref="hidden"/>
            <xs:attribute ref="trigger"/>
            <xs:attribute ref="condition"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="block">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"/>
                <xs:element ref="name"/>
            </xs:sequence>
            <xs:attribute ref="condition"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="source">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="url"/>
                <xs:element ref="interval"/>
                <xs:element ref="text"/>
                <xs:element ref="value"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="options">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="option" maxOccurs="10"/>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>        
    
    <xs:element name="path">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" minOccurs="0"/>
                <xs:element ref="parent" maxOccurs="10"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>   
    
    <xs:element name="option">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="condition" type="xs:string" />
                    <xs:attribute name="default" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="default">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="firstOnly" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="link">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="nameVal" type="xs:string" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="constraint">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="regex"/>
                <xs:element ref="message" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>  
    
    <xs:element name="bound">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="value"/>
                <xs:element ref="min" minOccurs="0"/>
                <xs:element ref="max" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>   
    
    <xs:element name="fulfilled">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="has" maxOccurs="unbounded"/>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>  
    
    <xs:element name="note">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="location"/>                
                <xs:element ref="size"/>
                <xs:element ref="text"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xi-yang/StackV.community/StackV-web/src/main/webapp/data/xml/ecc.xml
<?xml version="1.0" encoding="UTF-8"?>

<intent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="intent.xsd">
    <meta>
        <name>EdgeCloud Connection</name>
        <validation>
            <constraint>
                <name>string</name>
                <regex>\S+</regex>
                <message>Please enter a valid string.</message>
            </constraint>
            <constraint>
                <name>integer</name>
                <regex>\d+</regex>
                <message>Please enter a valid integer.</message>
            </constraint>
            <constraint>
                <name>select</name>
                <regex>.+</regex>
                <message>Please select a valid option.</message>
            </constraint>
            <constraint>
                <name>vlan</name>
                <regex>^\d{1,4}$|^\d{1,4}-\d{1,4}$|^any$</regex>
                <message>Please enter a valid VLAN.</message>
            </constraint>
            <constraint>
                <name>macs</name>
                <regex>^\w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2}(,\w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2})*$</regex>
                <message>Please enter a valid comma-separated list of MAC addresses.</message>
            </constraint>
            <constraint>
                <name>ip</name>
                <regex>^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{2}$</regex>
                <message>Please enter a valid IP address.</message>
            </constraint>
        </validation>
    </meta>
    <stage name="Connections">
        <group name="Cloud Details">
            <input required="true">
                <name>Provider</name>
                <type>select</type>
                <options>
                    <option>Amazon</option>
                </options>
                <valid>select</valid>
            </input>
            <input>
                <name>URI</name>
                <type>select</type>
                <source>
                    <url>/driver</url>
                    <interval>3</interval>
                    <text>3</text>
                    <value>3</value>
                </source>
                <valid>select</valid>
            </input>
        </group>
        <group factory="true" name="Connection" collapsible="true" opened="true">            
            <group name="Direct Connect" passthrough="true">
                <input required="true">
                    <name>Owner Account</name>
                    <type>text</type>
                    <valid>integer</valid>
                </input>
                <input>
                    <name>L3 Customer IP</name>
                    <type>text</type>
                    <default>10.10.0.1/24</default>
                    <valid>ip</valid>                   
                </input>
                <input>
                    <name>L3 CloudEdge IP</name>
                    <type>text</type>
                    <default>10.10.0.2/24</default>
                    <valid>ip</valid>
                </input>
                <input>
                    <name>L3 Customer ASN</name>
                    <type>text</type>
                    <default>65001</default>
                    <size>small</size>
                    <valid>integer</valid>
                </input>
                <input>
                    <name>L3 Authentication Key</name>
                    <type>text</type>
                    <default>stackv</default>
                    <valid>string</valid>
                </input>
            </group>
            <group name="Terminal" passthrough="true">
                <input>
                    <name>L2 Customer VLAN</name>
                    <type>text</type>
                    <default>any</default>
                    <size>small</size>
                    <valid>VLAN</valid>
                </input>
                <input>
                    <name>Bandwidth Limit</name>
                    <type>text</type>
                    <hint>in Mbps</hint>
                    <size>small</size>
                </input>
                <input required="true">
                    <name>L2 Customer URI</name>
                    <type>text</type>
                    <valid>string</valid>
                </input>
            </group>
        </group>
    </stage>
</intent>

=== xi-yang/StackV.community/StackV-web/src/main/webapp/data/xml/ec.xml
<?xml version="1.0" encoding="UTF-8"?>

<intent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="intent.xsd">
    <meta>
        <name>EdgeCloud Service</name>
        <validation>
            <constraint>
                <name>string</name>
                <regex>\S+</regex>
                <message>Please enter a valid string.</message>
            </constraint>
            <constraint>
                <name>integer</name>
                <regex>\d+</regex>
                <message>Please enter a valid integer.</message>
            </constraint>
            <constraint>
                <name>vlan</name>
                <regex>^\d{1,4}$|^\d{1,4}-\d{1,4}$|^any$</regex>
                <message>Please enter a valid VLAN.</message>
            </constraint>
            <constraint>
                <name>macs</name>
                <regex>^\w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2}(,\w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2})*$</regex>
                <message>Please enter a valid comma-separated list of MAC addresses.</message>
            </constraint>
            <constraint>
                <name>cidr</name>
                <regex>^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{2}$</regex>
                <message>Please enter a valid CIDR.</message>
            </constraint>
        </validation>
    </meta>
    <stage name="Connection">
        <group name="AWS Direct Connect">
            <input required="true">
                <name>Owner Account Number</name>
                <type>text</type>
                <valid>integer</valid>
            </input>
            <input>
                <name>Customer IP</name>
                <type>text</type>
                <valid>ip</valid>
            </input>
            <input>
                <name>Amazon IP</name>
                <type>text</type>
                <valid>ip</valid>
            </input>
            <input>
                <name>Customer ASN</name>
                <type>text</type>
                <valid>integer</valid>
            </input>
            <input>
                <name>Authentication Key</name>
                <type>text</type>
                <valid>string</valid>
            </input>
        </group>
        <group name="Terminal">
            <input>
                <name>URI</name>
                <type>text</type>
                <valid>string</valid>
            </input>
            <input>
                <name>VLAN Tag</name>
                <type>text</type>
                <valid>VLAN</valid>
            </input>
            <input>
                <name>Bandwidth</name>
                <type>text</type>
                <valid>string</valid>
            </input>
        </group>
    </stage>
</intent>

=== xi-yang/StackV.community/StackV-web/src/main/webapp/data/xml/dnc.xml
<?xml version="1.0" encoding="UTF-8"?>

<intent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="intent.xsd">
    <meta>
        <name>Dynamic Network Connection</name>
        <validation>
            <constraint>
                <name>string</name>
                <regex>\S+</regex>
                <message>Please enter a valid string.</message>
            </constraint>
            <constraint>
                <name>integer</name>
                <regex>\d+</regex>
                <message>Please enter a valid integer.</message>
            </constraint>
            <constraint>
                <name>vlan</name>
                <regex>^\d{1,4}$|^\d{1,4}-\d{1,4}$|^any$</regex>
                <message>Please enter a valid VLAN.</message>
            </constraint>
            <constraint>
                <name>macs</name>
                <regex>^\w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2}(,\w{2}:\w{2}:\w{2}:\w{2}:\w{2}:\w{2})*$</regex>
                <message>Please enter a valid comma-separated list of MAC addresses.</message>
            </constraint>
            <constraint>
                <name>cidr</name>
                <regex>^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{2}$</regex>
                <message>Please enter a valid CIDR.</message>
            </constraint>
        </validation>
    </meta>
    <stage name="Connections">
        <input required="true">
            <name>Type</name>
            <type>select</type>
            <options>
                <option default="true">Multi-Path P2P VLAN</option>
                <option>Multi-Point VLAN Bridge</option>
            </options>
        </input>
        <group factory="true" name="connection" collapsible="true" opened="true">
            <input>
                <name>Name</name>
                <type>text</type>
                <valid>string</valid>
            </input>
            <group name="Bandwidth" collapsible="true" opened="true">
                <input>
                    <name>Capacity</name>
                    <type>text</type>
                    <hint>(in Mbps)</hint>
                    <valid>integer</valid>
                </input>
                <input required="true">
                    <name>QoS Class</name>
                    <type>select</type>
                    <options>
                        <option>guaranteedCapped</option>
                        <option>softCapped</option>
                        <option>anyAvailable</option>
                        <option default="true">bestEffort</option>
                    </options>
                </input>
            </group>
            <group factory="true" name="terminal">
                <bound>
                    <name>connections-type</name>
                    <value>Multi-Path P2P VLAN</value>
                    <min>2</min>
                    <max>2</max>
                </bound>
                <bound>
                    <name>connections-type</name>
                    <value>Multi-Point VLAN Bridge</value>
                    <min>3</min>
                </bound>

                <input>
                    <name>URI</name>
                    <type>text</type>
                    <size>xlarge</size>
                    <valid>string</valid>
                </input>
                <input>
                    <name>VLAN Tag</name>
                    <type>text</type>
                    <default>any</default>
                    <size>small</size>
                    <valid>vlan</valid>
                </input>
                <input condition="type::Multi-Point VLAN Bridge">
                    <name>MAC Address List</name>
                    <type>text</type>
                    <size>small</size>
                    <valid>macs</valid>
                </input>
                <input>
                    <name>Assign IP</name>
                    <type>checkbox</type>
                    <size>small</size>
                </input>
            </group>
        </group>
        <group factory="true" name="IP Range" collapsible="true" opened="false">
            <input>
                <name>Start</name>
                <type>text</type>
                <hint>(A.B.C.D/Mask)</hint>
                <valid>cidr</valid>
            </input>
            <input>
                <name>End</name>
                <type>text</type>
                <hint>(A.B.C.D/Mask)</hint>
                <valid>cidr</valid>
            </input>
        </group>
    </stage>
</intent>
